# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marianne Corvellec
email: marianne.corvellec@ens-lyon.org
description: > # this means to ignore newlines until "baseurl:"
  I explore data and I build software. I am active in the community as a
  speaker, teacher, and event organizer. I live and work in Montréal, QC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mkcor.github.io" # the base hostname & protocol for your site
github_username: mkcor

# Build settings
markdown: kramdown
timezone: "America/New_York"

plugins:
  - jekyll-feed
